import {
  tripSchema,
  couponSchema,
  productSchema,
  dealGroupSchema,
  type Trip,
  type AppState,
} from "./models";
import { today, uid } from "./money";

export function demoTrip(): Trip {
  const products = [
    [
      "poise",
      "Poise Moderate Absorbency Pads",
      "Poise",
      "20 ct",
      2,
      799,
      "Personal care",
    ],
    ["aussie", "Aussie Hair Care", "Aussie", "", 2, 579, "Hair"],
    ["nexxus", "Nexxus Hair Care Mask", "Nexxus", "", 2, 579, "Hair"],
    ["shea1", "Shea Moisture Hair Care", "Shea Moisture", "", 1, 1099, "Hair"],
    ["shea2", "Shea Moisture Hair Care", "Shea Moisture", "", 1, 1199, "Hair"],
    [
      "mouthwash",
      "Colgate Total Gum Health Mouthwash",
      "Colgate",
      "16.9 oz",
      2,
      549,
      "Oral care",
    ],
    [
      "optic",
      "Colgate Optic White Advanced Toothpaste",
      "Colgate",
      "3.2 oz",
      2,
      699,
      "Oral care",
    ],
    [
      "pro",
      "Colgate Optic White Pro Series Toothpaste",
      "Colgate",
      "3 oz",
      1,
      1179,
      "Oral care",
    ],
    [
      "total",
      "Colgate Total Whitening Toothpaste",
      "Colgate",
      "3.3 oz",
      2,
      499,
      "Oral care",
    ],
    [
      "gain",
      "Gain + Odor Defense Laundry Detergent",
      "Gain",
      "81 oz",
      1,
      999,
      "Laundry",
    ],
    ["flings", "Gain Flings Laundry Pacs", "Gain", "31 ct", 1, 999, "Laundry"],
    [
      "tide",
      "Tide Original Laundry Detergent",
      "Tide",
      "29 fl oz",
      1,
      599,
      "Laundry",
    ],
    [
      "lotion",
      "Lubriderm Daily Moisture Lotion",
      "Lubriderm",
      "6 oz",
      2,
      469,
      "Personal care",
    ],
    [
      "soap",
      "Palmolive Ultra Oxy Dish Soap",
      "Palmolive",
      "20 fl oz",
      2,
      379,
      "Household",
    ],
  ].map(([id, name, brand, size, quantity, unitPrice, category]) =>
    productSchema.parse({
      id,
      name,
      brand,
      size,
      quantity,
      unitPrice,
      category,
    }),
  );
  const coupons = [
    {
      id: "poise-c",
      name: "$7 off 2 Poise",
      type: "manufacturer",
      value: 700,
      minimumQuantity: 2,
      productIds: ["poise"],
      stackingClass: "manufacturer",
    },
    {
      id: "aussie-c",
      name: "$3 off 2 Aussie",
      type: "manufacturer",
      value: 300,
      minimumQuantity: 2,
      productIds: ["aussie"],
      stackingClass: "manufacturer",
    },
    {
      id: "nexxus-c",
      name: "$9 off 2 Nexxus",
      type: "manufacturer",
      value: 900,
      minimumQuantity: 2,
      productIds: ["nexxus"],
      stackingClass: "manufacturer",
    },
    {
      id: "hair-c",
      name: "10OFF40HAIR — $10 off $40",
      type: "spend-save",
      value: 1000,
      minimumSpend: 4000,
      category: "Hair",
    },
    {
      id: "colgate-c",
      name: "$5 off $30 Colgate",
      type: "crt",
      value: 500,
      minimumSpend: 3000,
      brand: "Colgate",
    },
    {
      id: "lotion-c",
      name: "Lubriderm BOGO 40% off",
      type: "bogo-percentage",
      value: 0,
      percent: 40,
      productIds: ["lotion"],
      stackingClass: "promotion",
    },
    {
      id: "soap-c",
      name: "Palmolive BOGO 50% off",
      type: "bogo-percentage",
      value: 0,
      percent: 50,
      productIds: ["soap"],
      stackingClass: "promotion",
    },
  ].map((c) =>
    couponSchema.parse({
      ...c,
      quantity: 1,
      notes:
        "Illustrative demo; verify availability and terms in your CVS app.",
    }),
  );
  const groups = [
    {
      id: "poise-g",
      name: "Poise",
      productIds: ["poise"],
      minimumQuantity: 2,
      extraBucksReward: 700,
    },
    {
      id: "hair-g",
      name: "Hair deal",
      productIds: ["aussie", "nexxus", "shea1", "shea2"],
      minimumSpend: 4000,
      requiredCouponId: "hair-c",
    },
    {
      id: "colgate-g",
      name: "Colgate",
      productIds: ["mouthwash", "optic", "pro", "total"],
      minimumSpend: 3000,
      requiredCouponId: "colgate-c",
    },
    {
      id: "laundry-g",
      name: "Laundry",
      productIds: ["gain", "flings", "tide"],
      minimumSpend: 2500,
      extraBucksReward: 800,
    },
    {
      id: "lotion-g",
      name: "Lubriderm",
      productIds: ["lotion"],
      minimumQuantity: 2,
      extraBucksReward: 500,
    },
    {
      id: "soap-g",
      name: "Palmolive",
      productIds: ["soap"],
      minimumQuantity: 2,
      extraBucksReward: 300,
    },
  ].map((g) => dealGroupSchema.parse(g));
  return tripSchema.parse({
    id: uid(),
    name: "My $9 ExtraBucks demo",
    date: today(),
    startingExtraBucks: 900,
    products,
    coupons,
    groups,
    transactions: groups.map((g, i) => ({
      id: `demo-${i}`,
      name: g.name,
      productIds: g.productIds,
    })),
    createdAt: new Date().toISOString(),
    notes:
      "Example data, not verified live offers. No unspecified Colgate manufacturer discounts or rewards are assumed. Set your tax estimate before shopping.",
  });
}
export const blankTrip = (): Trip =>
  tripSchema.parse({
    id: uid(),
    name: "New shopping trip",
    date: today(),
    startingExtraBucks: 0,
    products: [],
    coupons: [],
    groups: [],
    transactions: [],
    createdAt: new Date().toISOString(),
  });
export const initialState = (): AppState => ({
  version: 1,
  trips: [demoTrip()],
  coupons: [],
  wallet: [],
  beginner: true,
});
